### ISSUE TITLE
If a student's school does not use the "house" system, the call to hexToRGB returns undefined

### ISSUE THREAD

**Issue by Crazypersonalph** [Crazypersonalph/HyperSEQTA#29]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'slice')
    at hexToRGB (SEQTA.js:2153:24)
    at GetThresholdofHex (SEQTA.js:2161:13)
    at SEQTA.js:1892:33
```

**Comment by Crazypersonalph** [comment]
Pretty simple fix, just check if the student has a house colour, then move from there.

**Comment by Crazypersonalph** [comment]
I believe this is actually unrelated to House colours, rather, to do with the document loading in

Due to how this is relatively minor, and doesn't actually affect anything, will leave this as not fixing
